// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguridadInformática.Data;

#nullable disable

namespace SeguridadInformática.Migrations
{
    [DbContext(typeof(SeguridadInformáticaContext))]
    partial class SeguridadInformáticaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RiesgoPorActivo", b =>
                {
                    b.Property<int>("Id_Activo")
                        .HasColumnType("int");

                    b.Property<int>("Id_Riesgo")
                        .HasColumnType("int");

                    b.HasKey("Id_Activo", "Id_Riesgo");

                    b.HasIndex("Id_Riesgo");

                    b.ToTable("RiesgoPorActivo");
                });

            modelBuilder.Entity("SeguridadInformática.Models.Activo", b =>
                {
                    b.Property<int>("Id_Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Activo"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Activo");

                    b.ToTable("Activo");
                });

            modelBuilder.Entity("SeguridadInformática.Models.Control", b =>
                {
                    b.Property<int>("Id_Control")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Control"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Control");

                    b.ToTable("Control");
                });

            modelBuilder.Entity("SeguridadInformática.Models.Dimension", b =>
                {
                    b.Property<int>("Id_Dimension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Dimension"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Dimension");

                    b.ToTable("Dimension");
                });

            modelBuilder.Entity("SeguridadInformática.Models.Riesgo", b =>
                {
                    b.Property<int>("Id_Riesgo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Riesgo"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Riesgo");

                    b.ToTable("Riesgo");
                });

            modelBuilder.Entity("RiesgoPorActivo", b =>
                {
                    b.HasOne("SeguridadInformática.Models.Activo", "Activo")
                        .WithMany("RiesgosPorActivo")
                        .HasForeignKey("Id_Activo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeguridadInformática.Models.Riesgo", "Riesgo")
                        .WithMany("RiesgosPorActivo")
                        .HasForeignKey("Id_Riesgo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Riesgo");
                });

            modelBuilder.Entity("SeguridadInformática.Models.Activo", b =>
                {
                    b.Navigation("RiesgosPorActivo");
                });

            modelBuilder.Entity("SeguridadInformática.Models.Riesgo", b =>
                {
                    b.Navigation("RiesgosPorActivo");
                });
#pragma warning restore 612, 618
        }
    }
}
